### ISSUE TITLE
About the behavior when jumping to next video with the comment expanded.

### ISSUE THREAD

**Issue by 1natsu172** [dideler/toggle-youtube-comments#19]
## Problem 👎 

In the current version, we can not support page jumping, so if you jump to a different movie with the comment expanded, comments will still be expanded on the next page.

## solution ⚙️ 

Want to detect dynamic render by ShadyDOM's page jump.
This makes it possible to perform the Inject of the toggleButton again when jumping the page.

Without using the chrome.tabs API, page jumping can probably be determined by using `document.addEventListener('yt-page-data-updated', fn);`.

***

If extension could solve this Issue, I thought that I could fundamentally solve Issue(#2)… 🤔 
But in reality this issue(#2) was another problem. So even if we support ShadyDOM's page jump, we can not solve Isssue(#2) :man_facepalming:

**Comment by 1natsu172** [comment]
> document.addEventListener('yt-page-data-updated', fn);

I think it works well. Extension can detect page jump.
So will submit PullRequest later. 🙏

**Comment by dideler** [comment]
Hey @1natsu172, this behaviour is intended. I thought it would be least surprising behaviour if the extension "remembered" your preference when switching videos. The YouTube experience between videos is very seamless and videos will often play automatically, so I view it as choosing to toggle comments while using YouTube, not just a specific video. Another way to look at it is if you're in the mood to view comments, it may be more annoying having the comments hiding when going to the next video because you would need to keep showing them manually.

But I may have been thinking about this the wrong way. I'll think more about it and ask other users what they think the behaviour should be. I want to go with the behaviour that best serves the users's needs.

**Comment by 1natsu172** [comment]
Oh…! I'm sorry @dideler 🙇 

I wasn't able to consider who thinks that users don't want to manually expand comments every time.
Certainly we should have discussed more about this behavior.

I think that users would like to basically hide comments in any videos using extensions or not.
For example, users may want to read comments on the next movie when watching a series of movies ...
In such cases, it may be annoying to have to expand comments every time.

Let's wait for opinions from other users.
Would you like to create a new issue topic for your opinion?

**Comment by dideler** [comment]
I've asked two people so far what their expected behaviour would be and they had the same idea as you, that is, hide comments automatically when switching to a new video. I'll talk to a few more people to see what they think. Let's keep this open and continue the discussion here.

**Comment by 1natsu172** [comment]
OK! Let's continue discussion here.
Changed issue title to easy topic title for the public.

**Comment by dideler** [comment]
I've asked a few more people and the consensus on expected behaviour is that the comments should auto-hide when navigating between videos. I'm happy for this feature* to go ahead!

<sup>\* I'm calling it a feature instead of a bug since the original design was intended behaviour.</sup>

**Comment by 1natsu172** [comment]
Thank you for the survey. OK, let 's bring this feature to production.
However, there are many changes since I submitted this PR. Since I feel that be able to improve some number of comments method & this feature(page navigation). I'll refactor the PR contents and submit it again.

**Comment by 1natsu172** [comment]
Close: Implemented by PR #40 🌟
