### ISSUE TITLE
Button not being injected on New YouTube

### ISSUE THREAD

**Issue by dideler** [dideler/toggle-youtube-comments#31]
Hard navigate to this video https://www.youtube.com/watch?v=7a9lsGtVziM

Expected: comment toggle button appears
Actual: comment toggle button does not appear

**Comment by 1natsu172** [comment]
Oh, it certainly doesn't work well. :man_facepalming: 
It seems that problem with the  type of video with heart action to user comment by the creator(uploader).

I'm thinking about fixing but perhaps it feels like this…

```javascript
_isInfoPanelRendered(e) {
    return (
      typeof e !== 'undefined' &&
      e.type === 'yt-visibility-refresh' &&
      (
        e.target.tagName === 'YTD-ITEM-SECTION-RENDERER' || 
        e.target.tagName === 'YTD-COMMENT-ACTION-BUTTONS-RENDERER' // add this judgement
      )
    );
}
```

And in this video, node of the number of comments can't be taken either. As a measure, continue to judge until Node appears directly with `querySelector` & `MutationObserver`.

```javascript
document.querySelector('#count .count-text')
```

And for this type of video, `MutationObserver` will be processed first rather than `_isInfopanelRendered()` before.  I might add the process to wait for the "SHOW COMMENTS"  button be injected.
